# Generated by Django 5.2.12 on 2026-08-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsource',
            name='main_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reviewsource',
            name='parser_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewsource',
            name='tos_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewsource',
            name='tos_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reviewsource',
            name='source_type',
            field=models.CharField(choices=[('reddit', 'Reddit'), ('forum', 'Forum'), ('review_site', 'Serwis z recenzjami'), ('other', 'Inne')], max_length=20),
        ),
    ]
