# Generated by Django 5.2.12 on 2026-08-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_backfill_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
