# Generated by Django 5.2.12 on 2026-09-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_score_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
