# Generated by Django 5.2.12 on 2026-08-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.CharField(choices=[('electronics', 'Elektronika'), ('cosmetics', 'Kosmetyki'), ('household', 'Produkty użytkowe / dom')], default='electronics', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='spec_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
