# Generated by Django 5.2.12 on 2026-09-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_backfill_electronics_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_overview_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
